//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPortal.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cancellation
    {
        public Cancellation()
        {
            this.Refund = 0.0m;
        }
    
        public int TicketNo { get; set; }
        public decimal Refund { get; set; }
        public string UserServiced { get; set; }
        public System.DateTime CancelDate { get; set; }
        public string Comment { get; set; }
    
        public virtual Reservation Reservation { get; set; }
        public virtual User Operator { get; set; }
    }
}
