//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPortal.DataBase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SkySharkDbContainer : DbContext
    {
        public SkySharkDbContainer()
            : base("name=SkySharkDbContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<User> UserSet { get; set; }
        public virtual DbSet<FlightDetails> FlightDetailsSet { get; set; }
        public virtual DbSet<Reservation> ReservationSet { get; set; }
        public virtual DbSet<Cancellation> CancellationSet { get; set; }
        public virtual DbSet<Passenger> PassengerSet { get; set; }
    }
}
