//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPortal.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Passenger
    {
        public Passenger()
        {
            this.FareCollected = 0.0m;
            this.TotalTimesFlown = 0;
            this.Discount = 0F;
            this.Reservation = new HashSet<Reservation>();
        }
    
        public string ID { get; set; }
        public string Name { get; set; }
        public decimal FareCollected { get; set; }
        public int TotalTimesFlown { get; set; }
        public float Discount { get; set; }
    
        public virtual ICollection<Reservation> Reservation { get; set; }
    }
}
