//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPortal.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        public Reservation()
        {
            this.Fare = 0.0m;
            this.EMail = "Null";
        }
    
        public int TicketNo { get; set; }
        public string FlightNo { get; set; }
        public string ReservedBy { get; set; }
        public FlightClass ClassOfRes { get; set; }
        public decimal Fare { get; set; }
        public System.DateTime DateOfRes { get; set; }
        public ReservationStatus Status { get; set; }
        public string EMail { get; set; }
    
        public virtual FlightDetails Flight { get; set; }
        public virtual Cancellation Cancellation { get; set; }
        public virtual Passenger Passenger { get; set; }
    }
}
